name: Deploy the application to Google Cloud Run

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Test Container
    runs-on: ubuntu-latest
    env:
      authMode: ${{ secrets.AUTHMODE_FIREBASE }}
      firebaseApiKey: ${{ secrets.FIREBASE_APIKEY }}
      firebaseAuthDomain: ${{ secrets.FIREBASE_AUTHDOMAIN }}
      firebaseDatabaseUrl: ${{ secrets.FIREBASE_DATABASEURL }}
      firebaseProjectId: ${{ secrets.FIREBASE_PROJECTID }}
      firebaseStorageBucket: ${{ secrets.FIREBASE_STORAGEBUCKET }}
      firebaseMessagingSenderId: ${{ secrets.FIREBASE_MESSAGING_SENDERID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker
      # Build the Docker image
      - name: GCloud using Docker to Build and Test
        run: npm run gcloud:build
      # Push the Docker image to Google Container Registry
      - name: Publish the Docker image to Google Container Registry
        run: npm run gcloud:push
      # Deploy the Docker image to the GKE cluster
      - name: Deploy the Docker image to the GKE cluster
        run: npm run gcloud:deploy
